### ISSUE TITLE
Talents taken multiple times are shown multiple times

### ISSUE THREAD

**Issue by Txus5012** [Foundry-Workshop/token-action-hud-wfrp4e#10]
If a character has taken a talent multiple times, it will be shown in the TAH multiple times. Not a big issue, but it would be better if these talents are shown only once.
![TAH](https://github.com/Foundry-Workshop/token-action-hud-wfrp4e/assets/87753744/5d9301fc-4339-4b68-a139-fc6f556453a3)

**Comment by Forien** [comment]
Ah right, forgot WFRP4e doesn't care about `quantity` when it comes to talents and instead uses separate items. 

Never understood why and forgot.

Will fix soon :)
