### ISSUE TITLE
[BUG] Manual Effects label not localized

### ISSUE THREAD

**Issue by Txus5012** [Foundry-Workshop/token-action-hud-wfrp4e#17]
**Module Version:** v1.1.1

**Describe the bug**
Manual Effects label shows TOKENACTIONHUD.WFRP4E.MANUALEFFECTS

**Screenshots**
![TAH Manual Effects](https://github.com/Foundry-Workshop/token-action-hud-wfrp4e/assets/87753744/ab449271-2a7e-42c5-9201-40b88aa9c20d)

**Foundry Version:** v11.315

**Game System:** v7.1.5

**Comment by Forien** [comment]
Added localization string.

However, once your group was created it is _possible_ that you will not see the change, unless you either **manually rename the group**, or **reset the layout** to use defaults.
